### ISSUE TITLE
Little typo to fix

### ISSUE THREAD

**Issue by erich666** [meshula/LabCamera#1]
On https://github.com/meshula/labcamera in the readme is:

"aperature" - change to "aperture"

I decided to then toss the page into MS Word (it's the copy editor in me - I like your readme to look great). It also notes:

"It's up the an application" - to "It's up to the application"

"the camera's sensor The mount's transform" - need a period in there

"focussed" to "focused"

"the in focus range" is better as "the in-focus range"

**Comment by meshula** [comment]
Thank you kindly for the edits :) 

https://github.com/meshula/LabCamera/commit/d7024fe292cdb44cbf83d4e3e39c8a6cd25e8ede
